DROP TABLE IF EXISTS regions CASCADE;

CREATE TABLE regions(
  id SERIAL PRIMARY KEY,
  latitude INTEGER NOT NULL UNIQUE,
  longitude INTEGER NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);