DROP TABLE IF EXISTS regions CASCADE;

CREATE TABLE regions(
  id SERIAL PRIMARY KEY,
  latitude DECIMAL(18, 15) NOT NULL UNIQUE,
  longitude DECIMAL(18, 15) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);