DROP TABLE IF EXISTS songs CASCADE;

CREATE TABLE songs(
  id SERIAL PRIMARY KEY,
  song_name VARCHAR(50) NOT NULL UNIQUE,
  likes INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);